// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyUGVus8dUxob1BGb7yZRbIHrEUPNtjJk',
    appId: '1:1017042723673:web:fb185df9645f8f7220e248',
    messagingSenderId: '1017042723673',
    projectId: 'flutter-auth-app-b097d',
    authDomain: 'flutter-auth-app-b097d.firebaseapp.com',
    storageBucket: 'flutter-auth-app-b097d.firebasestorage.app',
    measurementId: 'G-1KT6GRMQN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77rSyrA0-IKUjyGgSFE29jkIu7gIu7Gs',
    appId: '1:1017042723673:android:02808cbc9477157420e248',
    messagingSenderId: '1017042723673',
    projectId: 'flutter-auth-app-b097d',
    storageBucket: 'flutter-auth-app-b097d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2KszIs93sFhjjqb9hh1dZ_FxSjYw46Q',
    appId: '1:1017042723673:ios:7fb8bc88d9911edd20e248',
    messagingSenderId: '1017042723673',
    projectId: 'flutter-auth-app-b097d',
    storageBucket: 'flutter-auth-app-b097d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR2KszIs93sFhjjqb9hh1dZ_FxSjYw46Q',
    appId: '1:1017042723673:ios:7fb8bc88d9911edd20e248',
    messagingSenderId: '1017042723673',
    projectId: 'flutter-auth-app-b097d',
    storageBucket: 'flutter-auth-app-b097d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyUGVus8dUxob1BGb7yZRbIHrEUPNtjJk',
    appId: '1:1017042723673:web:b009f814ca8eedf220e248',
    messagingSenderId: '1017042723673',
    projectId: 'flutter-auth-app-b097d',
    authDomain: 'flutter-auth-app-b097d.firebaseapp.com',
    storageBucket: 'flutter-auth-app-b097d.firebasestorage.app',
    measurementId: 'G-33SYFRMCXW',
  );
}
